### ISSUE TITLE
Graphical glitched & maybe switch the screens (3DS)

### ISSUE THREAD

**Issue by MrJPGames** [GowenGameDevOpenSource/tappy-plane#1]
Currently the game looks kinda weird on the bottom screen (the plane morphs when rotating). There are also other things that look a little strange (scaled down, but in a without antialiasing).

Also IMO it would look better if the game was on the top screen and the instruction image was on the bottom screen.

**Comment by ghost** [comment]
Jasper,

I appreciate the feedback!

The main reason for the stretching is because this is a straight port of the mobile phone version which is in portrait.

The reason I put the game on the bottom screen is because it is closer to a portrait aspect ratio than the top screen, but ultimately, either way is landscape, so there is going to be stretching regardless.

One thing I could do would be to render the game across both screens (essentially making a portrait screen out of both screens), but I'm not sure if that would negatively affect the plane visibility.

Is rendering across both screens a common thing? The alternative would be for me to just zoom out the camera a bit horizontally, but only on the 3DS version.

Thanks again!

-----Original Message-----

**Comment by MrJPGames** [comment]
Though it's certainly common to see both screens utilised (at least on DS so 3DS shouldn't make to big of a difference). I do not however think that would be very good, it would probably become a little challenging to play the game. Zooming out the camera seems like a better idea, if there is now way for you to change the resolution of the camera to render it landscape.

**Comment by ghost** [comment]
MrJPGames,

![screen shot 2015-08-30 at 11 15 14 am](https://cloud.githubusercontent.com/assets/3932941/9568215/987782de-4f08-11e5-9576-ffaefdb43494.png)

How about this?

Please see the attached screenshot and build uploaded here: http://gowengamedev.com/misc/tappy-plane.3dsx

**Comment by MrJPGames** [comment]
I still feel it would work better on the top screen, but this is already good! If you want it to be on the bottom screen you can keep it this way, which screen is just a personal preference after all. 
You might want to add some fog effect to mask the game generating too slow, I feel that would work better than just seeing more of them as that might make the game easier.

In case you didn't know there is a site called gbatemp.net, you can make a thread for your games there, they also have a wiki with a list of games. It might help more people find your games!

**Comment by ghost** [comment]
Awesome, thanks so much man I appreciate it!

I will definitely check out gbatemp as well!

-----Original Message-----
